version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/code-editor
      - JWT_SECRET=your-secret-jwt-key-for-development
      - JWT_EXPIRATION=7d
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local